apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - host: mediawiki.hopto.org  # <--- ge채ndert, um auf alle Dienste zu verweisen
      http:
        paths:
          - pathType: Prefix
            path: "/jira"  # <--- eindeutigen Pfad hinzugef체gt
            backend:
              service:
                name: jira
                port:
                  number: 8080
          - pathType: Prefix
            path: "/mediawiki"  # <--- eindeutigen Pfad hinzugef체gt
            backend:
              service:
                name: mediawiki
                port:
                  number: 80
          - pathType: Prefix
            path: "/wordpress"  # <--- eindeutigen Pfad hinzugef체gt
            backend:
              service:
                name: wordpress
                port:
                  number: 30001
  # ...
